// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Problem.proto

package com.vv.personal.prom.artifactory.proto;

public interface AuthOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.Auth)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cred = 1;</code>
     */
    java.lang.String getCred();

    /**
     * <code>string cred = 1;</code>
     */
    com.google.protobuf.ByteString
    getCredBytes();

    /**
     * <code>bool isAuthorized = 2;</code>
     */
    boolean getIsAuthorized();
}
