// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CompanyList}
 */
public final class CompanyList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.CompanyList)
        CompanyListOrBuilder {
  public static final int COMPANY_FIELD_NUMBER = 1;

  // Use CompanyList.newBuilder() to construct.
  private CompanyList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.CompanyList)
  private static final com.vv.personal.prom.artifactory.proto.CompanyList DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<CompanyList>
          PARSER = new com.google.protobuf.AbstractParser<CompanyList>() {
    @java.lang.Override
    public CompanyList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompanyList(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.CompanyList();
  }

  private java.util.List<com.vv.personal.prom.artifactory.proto.Company> company_;
  private byte memoizedIsInitialized = -1;

  private CompanyList() {
    company_ = java.util.Collections.emptyList();
  }

  private CompanyList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              company_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Company>();
              mutable_bitField0_ |= 0x00000001;
            }
            company_.add(
                    input.readMessage(com.vv.personal.prom.artifactory.proto.Company.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        company_ = java.util.Collections.unmodifiableList(company_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<CompanyList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.CompanyList.class, com.vv.personal.prom.artifactory.proto.CompanyList.Builder.class);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
   */
  public java.util.List<com.vv.personal.prom.artifactory.proto.Company> getCompanyList() {
    return company_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
   */
  public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
  getCompanyOrBuilderList() {
    return company_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
   */
  public int getCompanyCount() {
    return company_.size();
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Company getCompany(int index) {
    return company_.get(index);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompanyOrBuilder(
          int index) {
    return company_.get(index);
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.CompanyList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < company_.size(); i++) {
      output.writeMessage(1, company_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < company_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, company_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.CompanyList)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.CompanyList other = (com.vv.personal.prom.artifactory.proto.CompanyList) obj;

    boolean result = true;
    result = result && getCompanyList()
            .equals(other.getCompanyList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCompanyCount() > 0) {
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder(); }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompanyList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CompanyList}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.CompanyList)
          com.vv.personal.prom.artifactory.proto.CompanyListOrBuilder {
    private int bitField0_;
    private java.util.List<com.vv.personal.prom.artifactory.proto.Company> company_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder> companyBuilder_;

    // Construct using com.vv.personal.prom.artifactory.proto.CompanyList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.CompanyList.class, com.vv.personal.prom.artifactory.proto.CompanyList.Builder.class);
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.CompanyList.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList build() {
      com.vv.personal.prom.artifactory.proto.CompanyList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCompanyFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (companyBuilder_ == null) {
        company_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        companyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList buildPartial() {
      com.vv.personal.prom.artifactory.proto.CompanyList result = new com.vv.personal.prom.artifactory.proto.CompanyList(this);
      int from_bitField0_ = bitField0_;
      if (companyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          company_ = java.util.Collections.unmodifiableList(company_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.company_ = company_;
      } else {
        result.company_ = companyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.CompanyList) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.CompanyList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.CompanyList other) {
      if (other == com.vv.personal.prom.artifactory.proto.CompanyList.getDefaultInstance()) return this;
      if (companyBuilder_ == null) {
        if (!other.company_.isEmpty()) {
          if (company_.isEmpty()) {
            company_ = other.company_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCompanyIsMutable();
            company_.addAll(other.company_);
          }
          onChanged();
        }
      } else {
        if (!other.company_.isEmpty()) {
          if (companyBuilder_.isEmpty()) {
            companyBuilder_.dispose();
            companyBuilder_ = null;
            company_ = other.company_;
            bitField0_ = (bitField0_ & ~0x00000001);
            companyBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getCompanyFieldBuilder() : null;
          } else {
            companyBuilder_.addAllMessages(other.company_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.CompanyList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.CompanyList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private void ensureCompanyIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        company_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Company>(company_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Company> getCompanyList() {
      if (companyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(company_);
      } else {
        return companyBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public int getCompanyCount() {
      if (companyBuilder_ == null) {
        return company_.size();
      } else {
        return companyBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company getCompany(int index) {
      if (companyBuilder_ == null) {
        return company_.get(index);
      } else {
        return companyBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder setCompany(
            int index, com.vv.personal.prom.artifactory.proto.Company value) {
      if (companyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyIsMutable();
        company_.set(index, value);
        onChanged();
      } else {
        companyBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder setCompany(
            int index, com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companyBuilder_ == null) {
        ensureCompanyIsMutable();
        company_.set(index, builderForValue.build());
        onChanged();
      } else {
        companyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder addCompany(com.vv.personal.prom.artifactory.proto.Company value) {
      if (companyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyIsMutable();
        company_.add(value);
        onChanged();
      } else {
        companyBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder addCompany(
            int index, com.vv.personal.prom.artifactory.proto.Company value) {
      if (companyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyIsMutable();
        company_.add(index, value);
        onChanged();
      } else {
        companyBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder addCompany(
            com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companyBuilder_ == null) {
        ensureCompanyIsMutable();
        company_.add(builderForValue.build());
        onChanged();
      } else {
        companyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder addCompany(
            int index, com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companyBuilder_ == null) {
        ensureCompanyIsMutable();
        company_.add(index, builderForValue.build());
        onChanged();
      } else {
        companyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder addAllCompany(
            java.lang.Iterable<? extends com.vv.personal.prom.artifactory.proto.Company> values) {
      if (companyBuilder_ == null) {
        ensureCompanyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, company_);
        onChanged();
      } else {
        companyBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder clearCompany() {
      if (companyBuilder_ == null) {
        company_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        companyBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public Builder removeCompany(int index) {
      if (companyBuilder_ == null) {
        ensureCompanyIsMutable();
        company_.remove(index);
        onChanged();
      } else {
        companyBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder getCompanyBuilder(
            int index) {
      return getCompanyFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompanyOrBuilder(
            int index) {
      if (companyBuilder_ == null) {
        return company_.get(index);
      } else {
        return companyBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompanyOrBuilderList() {
      if (companyBuilder_ != null) {
        return companyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(company_);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder addCompanyBuilder() {
      return getCompanyFieldBuilder().addBuilder(
              com.vv.personal.prom.artifactory.proto.Company.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder addCompanyBuilder(
            int index) {
      return getCompanyFieldBuilder().addBuilder(
              index, com.vv.personal.prom.artifactory.proto.Company.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Company.Builder>
    getCompanyBuilderList() {
      return getCompanyFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompanyFieldBuilder() {
      if (companyBuilder_ == null) {
        companyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>(
                company_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        company_ = null;
      }
      return companyBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.CompanyList)
  }

}

