// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Component.proto

package com.vv.personal.prom.artifactory.proto;

public final class ComponentProto {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_Component_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\017Component.proto\022&com.vv.personal.prom." +
                    "artifactory.proto\"e\n\tComponent\022X\n\023suppor" +
                    "tedComponents\030\001 \001(\0162;.com.vv.personal.pr" +
                    "om.artifactory.proto.SupportedComponents" +
                    "*E\n\023SupportedComponents\022\006\n\002LT\020\000\022\006\n\002MB\020\001\022" +
                    "\006\n\002SP\020\002\022\006\n\002SV\020\003\022\006\n\002SW\020\004\022\006\n\002RD\020\005B\022B\016Compo" +
                    "nentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_vv_personal_prom_artifactory_proto_Component_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor,
            new java.lang.String[]{"SupportedComponents",});
  }

  private ComponentProto() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
