// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Component.proto

package com.vv.personal.prom.artifactory.proto;

public interface ComponentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.Component)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 componentId = 1;</code>
     */
    int getComponentId();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    int getSupportedComponentsValue();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    com.vv.personal.prom.artifactory.proto.SupportedComponents getSupportedComponents();
}
