// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CompanyList}
 */
public final class CompanyList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.CompanyList)
        CompanyListOrBuilder {
  public static final int COMPANIES_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.CompanyList)
  private static final com.vv.personal.prom.artifactory.proto.CompanyList DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<CompanyList>
          PARSER = new com.google.protobuf.AbstractParser<CompanyList>() {
    @java.lang.Override
    public CompanyList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompanyList(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.CompanyList();
  }

  private java.util.List<com.vv.personal.prom.artifactory.proto.Company> companies_;
  private byte memoizedIsInitialized = -1;

  // Use CompanyList.newBuilder() to construct.
  private CompanyList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CompanyList() {
    companies_ = java.util.Collections.emptyList();
  }

  private CompanyList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              companies_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Company>();
              mutable_bitField0_ |= 0x00000001;
            }
            companies_.add(
                    input.readMessage(com.vv.personal.prom.artifactory.proto.Company.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        companies_ = java.util.Collections.unmodifiableList(companies_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.CompanyList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<CompanyList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.CompanyList.class, com.vv.personal.prom.artifactory.proto.CompanyList.Builder.class);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
   */
  public java.util.List<com.vv.personal.prom.artifactory.proto.Company> getCompaniesList() {
    return companies_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
   */
  public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
  getCompaniesOrBuilderList() {
    return companies_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
   */
  public int getCompaniesCount() {
    return companies_.size();
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Company getCompanies(int index) {
    return companies_.get(index);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompaniesOrBuilder(
          int index) {
    return companies_.get(index);
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < companies_.size(); i++) {
      output.writeMessage(1, companies_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < companies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, companies_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.CompanyList)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.CompanyList other = (com.vv.personal.prom.artifactory.proto.CompanyList) obj;

    boolean result = true;
    result = result && getCompaniesList()
            .equals(other.getCompaniesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCompaniesCount() > 0) {
      hash = (37 * hash) + COMPANIES_FIELD_NUMBER;
      hash = (53 * hash) + getCompaniesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompanyList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CompanyList}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.CompanyList)
          com.vv.personal.prom.artifactory.proto.CompanyListOrBuilder {
    private int bitField0_;
    private java.util.List<com.vv.personal.prom.artifactory.proto.Company> companies_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder> companiesBuilder_;

    // Construct using com.vv.personal.prom.artifactory.proto.CompanyList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.CompanyList.class, com.vv.personal.prom.artifactory.proto.CompanyList.Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCompaniesFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (companiesBuilder_ == null) {
        companies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        companiesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.CompanyList.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList build() {
      com.vv.personal.prom.artifactory.proto.CompanyList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CompanyList buildPartial() {
      com.vv.personal.prom.artifactory.proto.CompanyList result = new com.vv.personal.prom.artifactory.proto.CompanyList(this);
      int from_bitField0_ = bitField0_;
      if (companiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          companies_ = java.util.Collections.unmodifiableList(companies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.companies_ = companies_;
      } else {
        result.companies_ = companiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.CompanyList) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.CompanyList) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.CompanyList other) {
      if (other == com.vv.personal.prom.artifactory.proto.CompanyList.getDefaultInstance()) return this;
      if (companiesBuilder_ == null) {
        if (!other.companies_.isEmpty()) {
          if (companies_.isEmpty()) {
            companies_ = other.companies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCompaniesIsMutable();
            companies_.addAll(other.companies_);
          }
          onChanged();
        }
      } else {
        if (!other.companies_.isEmpty()) {
          if (companiesBuilder_.isEmpty()) {
            companiesBuilder_.dispose();
            companiesBuilder_ = null;
            companies_ = other.companies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            companiesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getCompaniesFieldBuilder() : null;
          } else {
            companiesBuilder_.addAllMessages(other.companies_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.CompanyList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.CompanyList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private void ensureCompaniesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        companies_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Company>(companies_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Company> getCompaniesList() {
      if (companiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(companies_);
      } else {
        return companiesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public int getCompaniesCount() {
      if (companiesBuilder_ == null) {
        return companies_.size();
      } else {
        return companiesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company getCompanies(int index) {
      if (companiesBuilder_ == null) {
        return companies_.get(index);
      } else {
        return companiesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder setCompanies(
            int index, com.vv.personal.prom.artifactory.proto.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.set(index, value);
        onChanged();
      } else {
        companiesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder setCompanies(
            int index, com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.set(index, builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder addCompanies(com.vv.personal.prom.artifactory.proto.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.add(value);
        onChanged();
      } else {
        companiesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder addCompanies(
            int index, com.vv.personal.prom.artifactory.proto.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.add(index, value);
        onChanged();
      } else {
        companiesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder addCompanies(
            com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.add(builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder addCompanies(
            int index, com.vv.personal.prom.artifactory.proto.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.add(index, builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder addAllCompanies(
            java.lang.Iterable<? extends com.vv.personal.prom.artifactory.proto.Company> values) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, companies_);
        onChanged();
      } else {
        companiesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder clearCompanies() {
      if (companiesBuilder_ == null) {
        companies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        companiesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public Builder removeCompanies(int index) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.remove(index);
        onChanged();
      } else {
        companiesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder getCompaniesBuilder(
            int index) {
      return getCompaniesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompaniesOrBuilder(
            int index) {
      if (companiesBuilder_ == null) {
        return companies_.get(index);
      } else {
        return companiesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompaniesOrBuilderList() {
      if (companiesBuilder_ != null) {
        return companiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(companies_);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder addCompaniesBuilder() {
      return getCompaniesFieldBuilder().addBuilder(
              com.vv.personal.prom.artifactory.proto.Company.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Company.Builder addCompaniesBuilder(
            int index) {
      return getCompaniesFieldBuilder().addBuilder(
              index, com.vv.personal.prom.artifactory.proto.Company.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Company.Builder>
    getCompaniesBuilderList() {
      return getCompaniesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompaniesFieldBuilder() {
      if (companiesBuilder_ == null) {
        companiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Company, com.vv.personal.prom.artifactory.proto.Company.Builder, com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>(
                companies_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        companies_ = null;
      }
      return companiesBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.CompanyList)
  }

}

