// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public interface CompanyListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.CompanyList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    java.util.List<com.vv.personal.prom.artifactory.proto.Company>
    getCompanyList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.Company getCompany(int index);

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    int getCompanyCount();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompanyOrBuilderList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company company = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompanyOrBuilder(
            int index);

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 2;</code>
     */
    boolean hasAuth();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 2;</code>
     */
    com.vv.personal.prom.artifactory.proto.Auth getAuth();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 2;</code>
     */
    com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder();
}
