// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public interface CompanyListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.CompanyList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    java.util.List<com.vv.personal.prom.artifactory.proto.Company>
    getCompaniesList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.Company getCompanies(int index);

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    int getCompaniesCount();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    java.util.List<? extends com.vv.personal.prom.artifactory.proto.CompanyOrBuilder>
    getCompaniesOrBuilderList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Company companies = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompaniesOrBuilder(
            int index);
}
