// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Component.proto

package com.vv.personal.prom.artifactory.proto;

public interface ComponentListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.ComponentList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Component components = 1;</code>
     */
    java.util.List<com.vv.personal.prom.artifactory.proto.Component>
    getComponentsList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Component components = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.Component getComponents(int index);

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Component components = 1;</code>
     */
    int getComponentsCount();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Component components = 1;</code>
     */
    java.util.List<? extends com.vv.personal.prom.artifactory.proto.ComponentOrBuilder>
    getComponentsOrBuilderList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Component components = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.ComponentOrBuilder getComponentsOrBuilder(
            int index);
}
