// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Component.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.Component}
 */
public final class Component extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.Component)
        ComponentOrBuilder {
  public static final int COMPONENTID_FIELD_NUMBER = 1;

  // Use Component.newBuilder() to construct.
  private Component(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Component() {
    componentId_ = 0;
    supportedComponents_ = 0;
  }

  public static final int SUPPORTEDCOMPONENTS_FIELD_NUMBER = 2;
  public static final int AUTH_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.Component)
  private static final com.vv.personal.prom.artifactory.proto.Component DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<Component>
          PARSER = new com.google.protobuf.AbstractParser<Component>() {
    @java.lang.Override
    public Component parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Component(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.Component();
  }

  /**
   * <code>int32 componentId = 1;</code>
   */
  public int getComponentId() {
    return componentId_;
  }

  private int componentId_;
  private int supportedComponents_;

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
   */
  public int getSupportedComponentsValue() {
    return supportedComponents_;
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
   */
  public com.vv.personal.prom.artifactory.proto.SupportedComponents getSupportedComponents() {
    @SuppressWarnings("deprecation")
    com.vv.personal.prom.artifactory.proto.SupportedComponents result = com.vv.personal.prom.artifactory.proto.SupportedComponents.valueOf(supportedComponents_);
    return result == null ? com.vv.personal.prom.artifactory.proto.SupportedComponents.UNRECOGNIZED : result;
  }

  private com.vv.personal.prom.artifactory.proto.Auth auth_;
  private byte memoizedIsInitialized = -1;

  private Component(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            componentId_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            supportedComponents_ = rawValue;
            break;
          }
          case 26: {
            com.vv.personal.prom.artifactory.proto.Auth.Builder subBuilder = null;
            if (auth_ != null) {
              subBuilder = auth_.toBuilder();
            }
            auth_ = input.readMessage(com.vv.personal.prom.artifactory.proto.Auth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auth_);
              auth_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.ComponentProto.internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Component parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.Component prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.vv.personal.prom.artifactory.proto.Component getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<Component> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.ComponentProto.internal_static_com_vv_personal_prom_artifactory_proto_Component_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.Component.class, com.vv.personal.prom.artifactory.proto.Component.Builder.class);
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public boolean hasAuth() {
    return auth_ != null;
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Auth getAuth() {
    return auth_ == null ? com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder() {
    return getAuth();
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (componentId_ != 0) {
      output.writeInt32(1, componentId_);
    }
    if (supportedComponents_ != com.vv.personal.prom.artifactory.proto.SupportedComponents.LT.getNumber()) {
      output.writeEnum(2, supportedComponents_);
    }
    if (auth_ != null) {
      output.writeMessage(3, getAuth());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (componentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, componentId_);
    }
    if (supportedComponents_ != com.vv.personal.prom.artifactory.proto.SupportedComponents.LT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
              .computeEnumSize(2, supportedComponents_);
    }
    if (auth_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(3, getAuth());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.Component)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.Component other = (com.vv.personal.prom.artifactory.proto.Component) obj;

    boolean result = true;
    result = result && (getComponentId()
            == other.getComponentId());
    result = result && supportedComponents_ == other.supportedComponents_;
    result = result && (hasAuth() == other.hasAuth());
    if (hasAuth()) {
      result = result && getAuth()
              .equals(other.getAuth());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMPONENTID_FIELD_NUMBER;
    hash = (53 * hash) + getComponentId();
    hash = (37 * hash) + SUPPORTEDCOMPONENTS_FIELD_NUMBER;
    hash = (53 * hash) + supportedComponents_;
    if (hasAuth()) {
      hash = (37 * hash) + AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getAuth().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Component> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.Component getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.Component}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.Component)
          com.vv.personal.prom.artifactory.proto.ComponentOrBuilder {
    private int componentId_;
    private int supportedComponents_ = 0;

    // Construct using com.vv.personal.prom.artifactory.proto.Component.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private com.vv.personal.prom.artifactory.proto.Auth auth_ = null;

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder> authBuilder_;

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Component getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.Component.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Component build() {
      com.vv.personal.prom.artifactory.proto.Component result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.ComponentProto.internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.ComponentProto.internal_static_com_vv_personal_prom_artifactory_proto_Component_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.Component.class, com.vv.personal.prom.artifactory.proto.Component.Builder.class);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      componentId_ = 0;

      supportedComponents_ = 0;

      if (authBuilder_ == null) {
        auth_ = null;
      } else {
        auth_ = null;
        authBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.ComponentProto.internal_static_com_vv_personal_prom_artifactory_proto_Component_descriptor;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Component buildPartial() {
      com.vv.personal.prom.artifactory.proto.Component result = new com.vv.personal.prom.artifactory.proto.Component(this);
      result.componentId_ = componentId_;
      result.supportedComponents_ = supportedComponents_;
      if (authBuilder_ == null) {
        result.auth_ = auth_;
      } else {
        result.auth_ = authBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.Component) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.Component) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    /**
     * <code>int32 componentId = 1;</code>
     */
    public int getComponentId() {
      return componentId_;
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.Component other) {
      if (other == com.vv.personal.prom.artifactory.proto.Component.getDefaultInstance()) return this;
      if (other.getComponentId() != 0) {
        setComponentId(other.getComponentId());
      }
      if (other.supportedComponents_ != 0) {
        setSupportedComponentsValue(other.getSupportedComponentsValue());
      }
      if (other.hasAuth()) {
        mergeAuth(other.getAuth());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.Component parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.Component) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    public int getSupportedComponentsValue() {
      return supportedComponents_;
    }
    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    public Builder setSupportedComponentsValue(int value) {
      supportedComponents_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    public com.vv.personal.prom.artifactory.proto.SupportedComponents getSupportedComponents() {
      @SuppressWarnings("deprecation")
      com.vv.personal.prom.artifactory.proto.SupportedComponents result = com.vv.personal.prom.artifactory.proto.SupportedComponents.valueOf(supportedComponents_);
      return result == null ? com.vv.personal.prom.artifactory.proto.SupportedComponents.UNRECOGNIZED : result;
    }

    /**
     * <code>int32 componentId = 1;</code>
     */
    public Builder setComponentId(int value) {

      componentId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 componentId = 1;</code>
     */
    public Builder clearComponentId() {

      componentId_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    public Builder setSupportedComponents(com.vv.personal.prom.artifactory.proto.SupportedComponents value) {
      if (value == null) {
        throw new NullPointerException();
      }

      supportedComponents_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.SupportedComponents supportedComponents = 2;</code>
     */
    public Builder clearSupportedComponents() {

      supportedComponents_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public boolean hasAuth() {
      return authBuilder_ != null || auth_ != null;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Auth getAuth() {
      if (authBuilder_ == null) {
        return auth_ == null ? com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
      } else {
        return authBuilder_.getMessage();
      }
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder setAuth(com.vv.personal.prom.artifactory.proto.Auth value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auth_ = value;
        onChanged();
      } else {
        authBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder setAuth(
            com.vv.personal.prom.artifactory.proto.Auth.Builder builderForValue) {
      if (authBuilder_ == null) {
        auth_ = builderForValue.build();
        onChanged();
      } else {
        authBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder mergeAuth(com.vv.personal.prom.artifactory.proto.Auth value) {
      if (authBuilder_ == null) {
        if (auth_ != null) {
          auth_ =
                  com.vv.personal.prom.artifactory.proto.Auth.newBuilder(auth_).mergeFrom(value).buildPartial();
        } else {
          auth_ = value;
        }
        onChanged();
      } else {
        authBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder clearAuth() {
      if (authBuilder_ == null) {
        auth_ = null;
        onChanged();
      } else {
        auth_ = null;
        authBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Auth.Builder getAuthBuilder() {

      onChanged();
      return getAuthFieldBuilder().getBuilder();
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder() {
      if (authBuilder_ != null) {
        return authBuilder_.getMessageOrBuilder();
      } else {
        return auth_ == null ?
                com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
      }
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder>
    getAuthFieldBuilder() {
      if (authBuilder_ == null) {
        authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder>(
                getAuth(),
                getParentForChildren(),
                isClean());
        auth_ = null;
      }
      return authBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.Component)
  }

}

