// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public final class CustomerProto {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_Customer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\016Customer.proto\022&com.vv.personal.prom.a" +
                    "rtifactory.proto\"[\n\010Customer\022\022\n\ncustomer" +
                    "Id\030\001 \001(\005\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName\030" +
                    "\003 \001(\t\022\026\n\016contactNumbers\030\004 \003(\tB\021B\rCustome" +
                    "rProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_vv_personal_prom_artifactory_proto_Customer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor,
            new java.lang.String[]{"CustomerId", "FirstName", "LastName", "ContactNumbers",});
  }

  private CustomerProto() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
