// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public interface CustomerListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.CustomerList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customer = 1;</code>
     */
    java.util.List<com.vv.personal.prom.artifactory.proto.Customer>
    getCustomerList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customer = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.Customer getCustomer(int index);

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customer = 1;</code>
     */
    int getCustomerCount();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customer = 1;</code>
     */
    java.util.List<? extends com.vv.personal.prom.artifactory.proto.CustomerOrBuilder>
    getCustomerOrBuilderList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customer = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.CustomerOrBuilder getCustomerOrBuilder(
            int index);
}
