// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public final class CustomerProto {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_Company_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\016Customer.proto\022&com.vv.personal.prom.a" +
                    "rtifactory.proto\"\235\001\n\010Customer\022\022\n\ncustome" +
                    "rId\030\001 \001(\005\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName" +
                    "\030\003 \001(\t\022\026\n\016contactNumbers\030\004 \003(\t\022@\n\007compan" +
                    "y\030\005 \001(\0132/.com.vv.personal.prom.artifacto" +
                    "ry.proto.Company\"g\n\007Company\022\021\n\tcompanyId" +
                    "\030\001 \001(\005\022\023\n\013companyName\030\002 \001(\t\022\034\n\024companyCo" +
                    "ntactPerson\030\003 \001(\t\022\026\n\016contactNumbers\030\004 \003(" +
                    "\t\"S\n\014CustomerList\022C\n\tcustomers\030\001 \003(\01320.c" +
                    "om.vv.personal.prom.artifactory.proto.Cu" +
                    "stomer\"Q\n\013CompanyList\022B\n\tcompanies\030\001 \003(\013" +
                    "2/.com.vv.personal.prom.artifactory.prot" +
                    "o.CompanyB\021B\rCustomerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_vv_personal_prom_artifactory_proto_Customer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_Customer_descriptor,
            new java.lang.String[]{"CustomerId", "FirstName", "LastName", "ContactNumbers", "Company",});
    internal_static_com_vv_personal_prom_artifactory_proto_Company_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_vv_personal_prom_artifactory_proto_Company_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_Company_descriptor,
            new java.lang.String[]{"CompanyId", "CompanyName", "CompanyContactPerson", "ContactNumbers",});
    internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor,
            new java.lang.String[]{"Customers",});
    internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor =
            getDescriptor().getMessageTypes().get(3);
    internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_prom_artifactory_proto_CompanyList_descriptor,
            new java.lang.String[]{"Companies",});
  }

  private CustomerProto() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
