// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CustomerList}
 */
public final class CustomerList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.CustomerList)
        CustomerListOrBuilder {
  public static final int CUSTOMERS_FIELD_NUMBER = 1;

  // Use CustomerList.newBuilder() to construct.
  private CustomerList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CustomerList() {
    customers_ = java.util.Collections.emptyList();
  }

  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.CustomerList)
  private static final com.vv.personal.prom.artifactory.proto.CustomerList DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<CustomerList>
          PARSER = new com.google.protobuf.AbstractParser<CustomerList>() {
    @java.lang.Override
    public CustomerList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new CustomerList(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.CustomerList();
  }

  private java.util.List<com.vv.personal.prom.artifactory.proto.Customer> customers_;
  private byte memoizedIsInitialized = -1;

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
   */
  public java.util.List<com.vv.personal.prom.artifactory.proto.Customer> getCustomersList() {
    return customers_;
  }

  private CustomerList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              customers_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Customer>();
              mutable_bitField0_ |= 0x00000001;
            }
            customers_.add(
                    input.readMessage(com.vv.personal.prom.artifactory.proto.Customer.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        customers_ = java.util.Collections.unmodifiableList(customers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
   */
  public int getCustomersCount() {
    return customers_.size();
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Customer getCustomers(int index) {
    return customers_.get(index);
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCustomersCount() > 0) {
      hash = (37 * hash) + CUSTOMERS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.CustomerList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.vv.personal.prom.artifactory.proto.CustomerList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<CustomerList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.CustomerList.class, com.vv.personal.prom.artifactory.proto.CustomerList.Builder.class);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
   */
  public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CustomerOrBuilder>
  getCustomersOrBuilderList() {
    return customers_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.CustomerOrBuilder getCustomersOrBuilder(
          int index) {
    return customers_.get(index);
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < customers_.size(); i++) {
      output.writeMessage(1, customers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < customers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, customers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.CustomerList)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.CustomerList other = (com.vv.personal.prom.artifactory.proto.CustomerList) obj;

    boolean result = true;
    result = result && getCustomersList()
            .equals(other.getCustomersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder(); }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomerList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.CustomerList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.CustomerList}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.CustomerList)
          com.vv.personal.prom.artifactory.proto.CustomerListOrBuilder {
    private int bitField0_;
    private java.util.List<com.vv.personal.prom.artifactory.proto.Customer> customers_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Customer, com.vv.personal.prom.artifactory.proto.Customer.Builder, com.vv.personal.prom.artifactory.proto.CustomerOrBuilder> customersBuilder_;

    // Construct using com.vv.personal.prom.artifactory.proto.CustomerList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCustomersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (customersBuilder_ == null) {
        customers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        customersBuilder_.clear();
      }
      return this;
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CustomerList getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.CustomerList.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CustomerList build() {
      com.vv.personal.prom.artifactory.proto.CustomerList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.CustomerList buildPartial() {
      com.vv.personal.prom.artifactory.proto.CustomerList result = new com.vv.personal.prom.artifactory.proto.CustomerList(this);
      int from_bitField0_ = bitField0_;
      if (customersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          customers_ = java.util.Collections.unmodifiableList(customers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.customers_ = customers_;
      } else {
        result.customers_ = customersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.CustomerList.class, com.vv.personal.prom.artifactory.proto.CustomerList.Builder.class);
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.CustomerProto.internal_static_com_vv_personal_prom_artifactory_proto_CustomerList_descriptor;
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.CustomerList) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.CustomerList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.CustomerList other) {
      if (other == com.vv.personal.prom.artifactory.proto.CustomerList.getDefaultInstance()) return this;
      if (customersBuilder_ == null) {
        if (!other.customers_.isEmpty()) {
          if (customers_.isEmpty()) {
            customers_ = other.customers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCustomersIsMutable();
            customers_.addAll(other.customers_);
          }
          onChanged();
        }
      } else {
        if (!other.customers_.isEmpty()) {
          if (customersBuilder_.isEmpty()) {
            customersBuilder_.dispose();
            customersBuilder_ = null;
            customers_ = other.customers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            customersBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getCustomersFieldBuilder() : null;
          } else {
            customersBuilder_.addAllMessages(other.customers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.CustomerList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.CustomerList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private void ensureCustomersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        customers_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Customer>(customers_);
        bitField0_ |= 0x00000001;
       }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Customer> getCustomersList() {
      if (customersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(customers_);
      } else {
        return customersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public int getCustomersCount() {
      if (customersBuilder_ == null) {
        return customers_.size();
      } else {
        return customersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Customer getCustomers(int index) {
      if (customersBuilder_ == null) {
        return customers_.get(index);
      } else {
        return customersBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder setCustomers(
            int index, com.vv.personal.prom.artifactory.proto.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.set(index, value);
        onChanged();
      } else {
        customersBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder setCustomers(
            int index, com.vv.personal.prom.artifactory.proto.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.set(index, builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder addCustomers(com.vv.personal.prom.artifactory.proto.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.add(value);
        onChanged();
      } else {
        customersBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder addCustomers(
            int index, com.vv.personal.prom.artifactory.proto.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.add(index, value);
        onChanged();
      } else {
        customersBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder addCustomers(
            com.vv.personal.prom.artifactory.proto.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.add(builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder addCustomers(
            int index, com.vv.personal.prom.artifactory.proto.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.add(index, builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder addAllCustomers(
            java.lang.Iterable<? extends com.vv.personal.prom.artifactory.proto.Customer> values) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, customers_);
        onChanged();
      } else {
        customersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder clearCustomers() {
      if (customersBuilder_ == null) {
        customers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        customersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public Builder removeCustomers(int index) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.remove(index);
        onChanged();
      } else {
        customersBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Customer.Builder getCustomersBuilder(
            int index) {
      return getCustomersFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.CustomerOrBuilder getCustomersOrBuilder(
            int index) {
      if (customersBuilder_ == null) {
        return customers_.get(index);
      } else {
        return customersBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public java.util.List<? extends com.vv.personal.prom.artifactory.proto.CustomerOrBuilder>
    getCustomersOrBuilderList() {
      if (customersBuilder_ != null) {
        return customersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(customers_);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Customer.Builder addCustomersBuilder() {
      return getCustomersFieldBuilder().addBuilder(
              com.vv.personal.prom.artifactory.proto.Customer.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Customer.Builder addCustomersBuilder(
            int index) {
      return getCustomersFieldBuilder().addBuilder(
              index, com.vv.personal.prom.artifactory.proto.Customer.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Customer customers = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Customer.Builder>
    getCustomersBuilderList() {
      return getCustomersFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Customer, com.vv.personal.prom.artifactory.proto.Customer.Builder, com.vv.personal.prom.artifactory.proto.CustomerOrBuilder>
    getCustomersFieldBuilder() {
      if (customersBuilder_ == null) {
        customersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Customer, com.vv.personal.prom.artifactory.proto.Customer.Builder, com.vv.personal.prom.artifactory.proto.CustomerOrBuilder>(
                customers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        customers_ = null;
      }
      return customersBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.CustomerList)
  }

}

