// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.vv.personal.prom.artifactory.proto;

public interface CustomerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.Customer)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * assuming that there'll never be need to go to long
     * </pre>
     *
     * <code>int32 customerId = 1;</code>
     */
    int getCustomerId();

    /**
     * <code>string firstName = 2;</code>
     */
    java.lang.String getFirstName();

    /**
     * <code>string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
    getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     */
    java.lang.String getLastName();

    /**
     * <code>string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
    getLastNameBytes();

    /**
     * <code>repeated string contactNumbers = 4;</code>
     */
    java.util.List<java.lang.String>
    getContactNumbersList();

    /**
     * <code>repeated string contactNumbers = 4;</code>
     */
    int getContactNumbersCount();

    /**
     * <code>repeated string contactNumbers = 4;</code>
     */
    java.lang.String getContactNumbers(int index);

    /**
     * <code>repeated string contactNumbers = 4;</code>
     */
    com.google.protobuf.ByteString
    getContactNumbersBytes(int index);

    /**
     * <pre>
     * usually the need for this use-case is 121 =&gt; customer to company
     * </pre>
     *
     * <code>.com.vv.personal.prom.artifactory.proto.Company company = 5;</code>
     */
    boolean hasCompany();

    /**
     * <pre>
     * usually the need for this use-case is 121 =&gt; customer to company
     * </pre>
     *
     * <code>.com.vv.personal.prom.artifactory.proto.Company company = 5;</code>
     */
    com.vv.personal.prom.artifactory.proto.Company getCompany();

    /**
     * <pre>
     * usually the need for this use-case is 121 =&gt; customer to company
     * </pre>
     *
     * <code>.com.vv.personal.prom.artifactory.proto.Company company = 5;</code>
     */
    com.vv.personal.prom.artifactory.proto.CompanyOrBuilder getCompanyOrBuilder();
}
