// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Make.proto

package com.vv.personal.prom.artifactory.proto;

public interface MakeListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.MakeList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    java.util.List<com.vv.personal.prom.artifactory.proto.Make>
    getMakesList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.Make getMakes(int index);

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    int getMakesCount();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    java.util.List<? extends com.vv.personal.prom.artifactory.proto.MakeOrBuilder>
    getMakesOrBuilderList();

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    com.vv.personal.prom.artifactory.proto.MakeOrBuilder getMakesOrBuilder(
            int index);
}
