// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Make.proto

package com.vv.personal.prom.artifactory.proto;

public interface MakeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.prom.artifactory.proto.Make)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * assuming that there'll never be need to go to long
     * </pre>
     *
     * <code>int32 makeId = 1;</code>
     */
    int getMakeId();

    /**
     * <code>string makeName = 2;</code>
     */
    java.lang.String getMakeName();

    /**
     * <code>string makeName = 2;</code>
     */
    com.google.protobuf.ByteString
    getMakeNameBytes();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    boolean hasAuth();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    com.vv.personal.prom.artifactory.proto.Auth getAuth();

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder();
}
