// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Make.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.MakeList}
 */
public final class MakeList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.MakeList)
        MakeListOrBuilder {
  public static final int MAKES_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.MakeList)
  private static final com.vv.personal.prom.artifactory.proto.MakeList DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<MakeList>
          PARSER = new com.google.protobuf.AbstractParser<MakeList>() {
    @java.lang.Override
    public MakeList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new MakeList(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.MakeList();
  }

  private java.util.List<com.vv.personal.prom.artifactory.proto.Make> makes_;
  private byte memoizedIsInitialized = -1;

  // Use MakeList.newBuilder() to construct.
  private MakeList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private MakeList() {
    makes_ = java.util.Collections.emptyList();
  }

  private MakeList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              makes_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Make>();
              mutable_bitField0_ |= 0x00000001;
            }
            makes_.add(
                    input.readMessage(com.vv.personal.prom.artifactory.proto.Make.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        makes_ = java.util.Collections.unmodifiableList(makes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.MakeProto.internal_static_com_vv_personal_prom_artifactory_proto_MakeList_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.MakeList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.vv.personal.prom.artifactory.proto.MakeList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<MakeList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.MakeProto.internal_static_com_vv_personal_prom_artifactory_proto_MakeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.MakeList.class, com.vv.personal.prom.artifactory.proto.MakeList.Builder.class);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
   */
  public java.util.List<com.vv.personal.prom.artifactory.proto.Make> getMakesList() {
    return makes_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
   */
  public java.util.List<? extends com.vv.personal.prom.artifactory.proto.MakeOrBuilder>
  getMakesOrBuilderList() {
    return makes_;
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
   */
  public int getMakesCount() {
    return makes_.size();
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Make getMakes(int index) {
    return makes_.get(index);
  }

  /**
   * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
   */
  public com.vv.personal.prom.artifactory.proto.MakeOrBuilder getMakesOrBuilder(
          int index) {
    return makes_.get(index);
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < makes_.size(); i++) {
      output.writeMessage(1, makes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < makes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, makes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.MakeList)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.MakeList other = (com.vv.personal.prom.artifactory.proto.MakeList) obj;

    boolean result = true;
    result = result && getMakesList()
            .equals(other.getMakesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMakesCount() > 0) {
      hash = (37 * hash) + MAKES_FIELD_NUMBER;
      hash = (53 * hash) + getMakesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MakeList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.MakeList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.MakeList}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.MakeList)
          com.vv.personal.prom.artifactory.proto.MakeListOrBuilder {
    private int bitField0_;
    private java.util.List<com.vv.personal.prom.artifactory.proto.Make> makes_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Make, com.vv.personal.prom.artifactory.proto.Make.Builder, com.vv.personal.prom.artifactory.proto.MakeOrBuilder> makesBuilder_;

    // Construct using com.vv.personal.prom.artifactory.proto.MakeList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.MakeProto.internal_static_com_vv_personal_prom_artifactory_proto_MakeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.MakeProto.internal_static_com_vv_personal_prom_artifactory_proto_MakeList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.MakeList.class, com.vv.personal.prom.artifactory.proto.MakeList.Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMakesFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (makesBuilder_ == null) {
        makes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        makesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.MakeProto.internal_static_com_vv_personal_prom_artifactory_proto_MakeList_descriptor;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.MakeList getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.MakeList.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.MakeList build() {
      com.vv.personal.prom.artifactory.proto.MakeList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.MakeList buildPartial() {
      com.vv.personal.prom.artifactory.proto.MakeList result = new com.vv.personal.prom.artifactory.proto.MakeList(this);
      int from_bitField0_ = bitField0_;
      if (makesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          makes_ = java.util.Collections.unmodifiableList(makes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.makes_ = makes_;
      } else {
        result.makes_ = makesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.MakeList) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.MakeList) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.MakeList other) {
      if (other == com.vv.personal.prom.artifactory.proto.MakeList.getDefaultInstance()) return this;
      if (makesBuilder_ == null) {
        if (!other.makes_.isEmpty()) {
          if (makes_.isEmpty()) {
            makes_ = other.makes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMakesIsMutable();
            makes_.addAll(other.makes_);
          }
          onChanged();
        }
      } else {
        if (!other.makes_.isEmpty()) {
          if (makesBuilder_.isEmpty()) {
            makesBuilder_.dispose();
            makesBuilder_ = null;
            makes_ = other.makes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            makesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getMakesFieldBuilder() : null;
          } else {
            makesBuilder_.addAllMessages(other.makes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.MakeList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.MakeList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private void ensureMakesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        makes_ = new java.util.ArrayList<com.vv.personal.prom.artifactory.proto.Make>(makes_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Make> getMakesList() {
      if (makesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(makes_);
      } else {
        return makesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public int getMakesCount() {
      if (makesBuilder_ == null) {
        return makes_.size();
      } else {
        return makesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Make getMakes(int index) {
      if (makesBuilder_ == null) {
        return makes_.get(index);
      } else {
        return makesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder setMakes(
            int index, com.vv.personal.prom.artifactory.proto.Make value) {
      if (makesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakesIsMutable();
        makes_.set(index, value);
        onChanged();
      } else {
        makesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder setMakes(
            int index, com.vv.personal.prom.artifactory.proto.Make.Builder builderForValue) {
      if (makesBuilder_ == null) {
        ensureMakesIsMutable();
        makes_.set(index, builderForValue.build());
        onChanged();
      } else {
        makesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder addMakes(com.vv.personal.prom.artifactory.proto.Make value) {
      if (makesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakesIsMutable();
        makes_.add(value);
        onChanged();
      } else {
        makesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder addMakes(
            int index, com.vv.personal.prom.artifactory.proto.Make value) {
      if (makesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakesIsMutable();
        makes_.add(index, value);
        onChanged();
      } else {
        makesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder addMakes(
            com.vv.personal.prom.artifactory.proto.Make.Builder builderForValue) {
      if (makesBuilder_ == null) {
        ensureMakesIsMutable();
        makes_.add(builderForValue.build());
        onChanged();
      } else {
        makesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder addMakes(
            int index, com.vv.personal.prom.artifactory.proto.Make.Builder builderForValue) {
      if (makesBuilder_ == null) {
        ensureMakesIsMutable();
        makes_.add(index, builderForValue.build());
        onChanged();
      } else {
        makesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder addAllMakes(
            java.lang.Iterable<? extends com.vv.personal.prom.artifactory.proto.Make> values) {
      if (makesBuilder_ == null) {
        ensureMakesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, makes_);
        onChanged();
      } else {
        makesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder clearMakes() {
      if (makesBuilder_ == null) {
        makes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        makesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public Builder removeMakes(int index) {
      if (makesBuilder_ == null) {
        ensureMakesIsMutable();
        makes_.remove(index);
        onChanged();
      } else {
        makesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Make.Builder getMakesBuilder(
            int index) {
      return getMakesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.MakeOrBuilder getMakesOrBuilder(
            int index) {
      if (makesBuilder_ == null) {
        return makes_.get(index);
      } else {
        return makesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public java.util.List<? extends com.vv.personal.prom.artifactory.proto.MakeOrBuilder>
    getMakesOrBuilderList() {
      if (makesBuilder_ != null) {
        return makesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(makes_);
      }
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Make.Builder addMakesBuilder() {
      return getMakesFieldBuilder().addBuilder(
              com.vv.personal.prom.artifactory.proto.Make.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Make.Builder addMakesBuilder(
            int index) {
      return getMakesFieldBuilder().addBuilder(
              index, com.vv.personal.prom.artifactory.proto.Make.getDefaultInstance());
    }

    /**
     * <code>repeated .com.vv.personal.prom.artifactory.proto.Make makes = 1;</code>
     */
    public java.util.List<com.vv.personal.prom.artifactory.proto.Make.Builder>
    getMakesBuilderList() {
      return getMakesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Make, com.vv.personal.prom.artifactory.proto.Make.Builder, com.vv.personal.prom.artifactory.proto.MakeOrBuilder>
    getMakesFieldBuilder() {
      if (makesBuilder_ == null) {
        makesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Make, com.vv.personal.prom.artifactory.proto.Make.Builder, com.vv.personal.prom.artifactory.proto.MakeOrBuilder>(
                makes_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        makes_ = null;
      }
      return makesBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.MakeList)
  }

}

