// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Problem.proto

package com.vv.personal.prom.artifactory.proto;

/**
 * Protobuf type {@code com.vv.personal.prom.artifactory.proto.Problem}
 */
public final class Problem extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vv.personal.prom.artifactory.proto.Problem)
        ProblemOrBuilder {
  public static final int PROBLEMID_FIELD_NUMBER = 1;

  // Use Problem.newBuilder() to construct.
  private Problem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Problem() {
    problemId_ = 0;
    problemName_ = "";
  }

  public static final int PROBLEMNAME_FIELD_NUMBER = 2;
  public static final int AUTH_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.vv.personal.prom.artifactory.proto.Problem)
  private static final com.vv.personal.prom.artifactory.proto.Problem DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<Problem>
          PARSER = new com.google.protobuf.AbstractParser<Problem>() {
    @java.lang.Override
    public Problem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Problem(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new com.vv.personal.prom.artifactory.proto.Problem();
  }

  private int problemId_;
  private volatile java.lang.Object problemName_;
  private com.vv.personal.prom.artifactory.proto.Auth auth_;
  private byte memoizedIsInitialized = -1;

  private Problem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            problemId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            problemName_ = s;
            break;
          }
          case 26: {
            com.vv.personal.prom.artifactory.proto.Auth.Builder subBuilder = null;
            if (auth_ != null) {
              subBuilder = auth_.toBuilder();
            }
            auth_ = input.readMessage(com.vv.personal.prom.artifactory.proto.Auth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auth_);
              auth_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.vv.personal.prom.artifactory.proto.ProblemProto.internal_static_com_vv_personal_prom_artifactory_proto_Problem_descriptor;
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.vv.personal.prom.artifactory.proto.Problem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.vv.personal.prom.artifactory.proto.Problem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<Problem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.vv.personal.prom.artifactory.proto.ProblemProto.internal_static_com_vv_personal_prom_artifactory_proto_Problem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.vv.personal.prom.artifactory.proto.Problem.class, com.vv.personal.prom.artifactory.proto.Problem.Builder.class);
  }

  /**
   * <pre>
   * assuming that there'll never be need to go to long
   * </pre>
   *
   * <code>int32 problemId = 1;</code>
   */
  public int getProblemId() {
    return problemId_;
  }

  /**
   * <code>string problemName = 2;</code>
   */
  public java.lang.String getProblemName() {
    java.lang.Object ref = problemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      problemName_ = s;
      return s;
    }
  }

  /**
   * <code>string problemName = 2;</code>
   */
  public com.google.protobuf.ByteString
  getProblemNameBytes() {
    java.lang.Object ref = problemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      problemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public boolean hasAuth() {
    return auth_ != null;
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public com.vv.personal.prom.artifactory.proto.Auth getAuth() {
    return auth_ == null ? com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
  }

  /**
   * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
   */
  public com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder() {
    return getAuth();
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (problemId_ != 0) {
      output.writeInt32(1, problemId_);
    }
    if (!getProblemNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, problemName_);
    }
    if (auth_ != null) {
      output.writeMessage(3, getAuth());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (problemId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, problemId_);
    }
    if (!getProblemNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, problemName_);
    }
    if (auth_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(3, getAuth());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.vv.personal.prom.artifactory.proto.Problem)) {
      return super.equals(obj);
    }
    com.vv.personal.prom.artifactory.proto.Problem other = (com.vv.personal.prom.artifactory.proto.Problem) obj;

    boolean result = true;
    result = result && (getProblemId()
            == other.getProblemId());
    result = result && getProblemName()
            .equals(other.getProblemName());
    result = result && (hasAuth() == other.hasAuth());
    if (hasAuth()) {
      result = result && getAuth()
              .equals(other.getAuth());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROBLEMID_FIELD_NUMBER;
    hash = (53 * hash) + getProblemId();
    hash = (37 * hash) + PROBLEMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProblemName().hashCode();
    if (hasAuth()) {
      hash = (37 * hash) + AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getAuth().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Problem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vv.personal.prom.artifactory.proto.Problem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.vv.personal.prom.artifactory.proto.Problem}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vv.personal.prom.artifactory.proto.Problem)
          com.vv.personal.prom.artifactory.proto.ProblemOrBuilder {
    private int problemId_;
    private java.lang.Object problemName_ = "";

    // Construct using com.vv.personal.prom.artifactory.proto.Problem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private com.vv.personal.prom.artifactory.proto.Auth auth_ = null;

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder> authBuilder_;

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Problem getDefaultInstanceForType() {
      return com.vv.personal.prom.artifactory.proto.Problem.getDefaultInstance();
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Problem build() {
      com.vv.personal.prom.artifactory.proto.Problem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.vv.personal.prom.artifactory.proto.ProblemProto.internal_static_com_vv_personal_prom_artifactory_proto_Problem_descriptor;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.vv.personal.prom.artifactory.proto.ProblemProto.internal_static_com_vv_personal_prom_artifactory_proto_Problem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.vv.personal.prom.artifactory.proto.Problem.class, com.vv.personal.prom.artifactory.proto.Problem.Builder.class);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      problemId_ = 0;

      problemName_ = "";

      if (authBuilder_ == null) {
        auth_ = null;
      } else {
        auth_ = null;
        authBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.vv.personal.prom.artifactory.proto.ProblemProto.internal_static_com_vv_personal_prom_artifactory_proto_Problem_descriptor;
    }

    @java.lang.Override
    public com.vv.personal.prom.artifactory.proto.Problem buildPartial() {
      com.vv.personal.prom.artifactory.proto.Problem result = new com.vv.personal.prom.artifactory.proto.Problem(this);
      result.problemId_ = problemId_;
      result.problemName_ = problemName_;
      if (authBuilder_ == null) {
        result.auth_ = auth_;
      } else {
        result.auth_ = authBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vv.personal.prom.artifactory.proto.Problem) {
        return mergeFrom((com.vv.personal.prom.artifactory.proto.Problem) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vv.personal.prom.artifactory.proto.Problem other) {
      if (other == com.vv.personal.prom.artifactory.proto.Problem.getDefaultInstance()) return this;
      if (other.getProblemId() != 0) {
        setProblemId(other.getProblemId());
      }
      if (!other.getProblemName().isEmpty()) {
        problemName_ = other.problemName_;
        onChanged();
      }
      if (other.hasAuth()) {
        mergeAuth(other.getAuth());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.vv.personal.prom.artifactory.proto.Problem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vv.personal.prom.artifactory.proto.Problem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <pre>
     *assuming that there'll never be need to go to long
     * </pre>
     *
     * <code>int32 problemId = 1;</code>
     */
    public int getProblemId() {
      return problemId_;
    }

    /**
     * <pre>
     *assuming that there'll never be need to go to long
     * </pre>
     *
     * <code>int32 problemId = 1;</code>
     */
    public Builder setProblemId(int value) {

      problemId_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *assuming that there'll never be need to go to long
     * </pre>
     *
     * <code>int32 problemId = 1;</code>
     */
    public Builder clearProblemId() {

      problemId_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string problemName = 2;</code>
     */
    public java.lang.String getProblemName() {
      java.lang.Object ref = problemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        problemName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string problemName = 2;</code>
     */
    public Builder setProblemName(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      problemName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string problemName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getProblemNameBytes() {
      java.lang.Object ref = problemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        problemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string problemName = 2;</code>
     */
    public Builder setProblemNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      problemName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string problemName = 2;</code>
     */
    public Builder clearProblemName() {

      problemName_ = getDefaultInstance().getProblemName();
      onChanged();
      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public boolean hasAuth() {
      return authBuilder_ != null || auth_ != null;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Auth getAuth() {
      if (authBuilder_ == null) {
        return auth_ == null ? com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
      } else {
        return authBuilder_.getMessage();
      }
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder setAuth(com.vv.personal.prom.artifactory.proto.Auth value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auth_ = value;
        onChanged();
      } else {
        authBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder setAuth(
            com.vv.personal.prom.artifactory.proto.Auth.Builder builderForValue) {
      if (authBuilder_ == null) {
        auth_ = builderForValue.build();
        onChanged();
      } else {
        authBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder mergeAuth(com.vv.personal.prom.artifactory.proto.Auth value) {
      if (authBuilder_ == null) {
        if (auth_ != null) {
          auth_ =
                  com.vv.personal.prom.artifactory.proto.Auth.newBuilder(auth_).mergeFrom(value).buildPartial();
        } else {
          auth_ = value;
        }
        onChanged();
      } else {
        authBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public Builder clearAuth() {
      if (authBuilder_ == null) {
        auth_ = null;
        onChanged();
      } else {
        auth_ = null;
        authBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.Auth.Builder getAuthBuilder() {

      onChanged();
      return getAuthFieldBuilder().getBuilder();
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    public com.vv.personal.prom.artifactory.proto.AuthOrBuilder getAuthOrBuilder() {
      if (authBuilder_ != null) {
        return authBuilder_.getMessageOrBuilder();
      } else {
        return auth_ == null ?
                com.vv.personal.prom.artifactory.proto.Auth.getDefaultInstance() : auth_;
      }
    }

    /**
     * <code>.com.vv.personal.prom.artifactory.proto.Auth auth = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder>
    getAuthFieldBuilder() {
      if (authBuilder_ == null) {
        authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.vv.personal.prom.artifactory.proto.Auth, com.vv.personal.prom.artifactory.proto.Auth.Builder, com.vv.personal.prom.artifactory.proto.AuthOrBuilder>(
                getAuth(),
                getParentForChildren(),
                isClean());
        auth_ = null;
      }
      return authBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vv.personal.prom.artifactory.proto.Problem)
  }

}

